# Generated by Django 4.2.7 on 2023-11-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_long', models.CharField(max_length=300)),
                ('url_short', models.CharField(blank=True, max_length=150)),
                ('qr_code', models.ImageField(upload_to='qr_codes')),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
